---
- name: start openvpn
  systemd:
    name: openvpn-server@server
    state: started
    enabled: True

- name: start ufw
  systemd:
    name: ufw
    enabled: yes
    state: started

- name: restart ufw
  systemd:
    name: ufw
    enabled: yes
    state: restarted
