---
- name: OpenVPN deploy on Ubuntu and Arch Hosts
  hosts: vpn
  remote_user: root
  become: true
  vars:
    send_client_profile_to: "someone@gmail.com"
  pre_tasks:
    - { include: tasks/main.yml }
  roles:
    - { role: openvpn, tags: [ 'openvpn' ] }
    - { role: easy-rsa, tags: [ 'rsa' ] }
    - { role: network, tags: [ 'network' ] }
    - { role: client, when: client_enable, tags: [ 'client' ] }

  post_tasks:
    - { include: tasks/post.yml }
