---
- name: Enable IPv4 traffic forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: yes

- include: iptables.yaml
  when: (iptables_enable) and (ufw_enable == False)
  ignore_errors: True

- include: ufw.yaml
  when: (ufw_enable) and (iptables_enable == False)
