---
- name: Send email with attached OpenVPN client profile
  mail:
    host: "{{ mailhost }}"
    port: "{{ mailport }}"
    secure: "{{ mailsecure }}"
    subtype: plain
    from: "{{ mailname }} <{{ mailfrom }}>"
    to: "<{{ mailto }}>"
    subject: "{{ mailsubject }}"
    body: "Hello,


    Your {{ key_org }} OpenVPN client profile is embedded into this email. Save the contents with a
    .ovpn extension to a file like openvpn-client.ovpn so the profile can be imported into supported OpenVPN desktop and mobile clients.


    Cheers,

    VPN staff

    {{ mailfrom }}


    ------copy below------



          {{ lookup('template', '{{ mailtemplate }}') }}
          "
  tags: email
  when: inventory_hostname in groups['vpn_primary']
