- include_tasks: arch.yaml
  when: (ansible_os_family|lower == 'archlinux') and (inventory_hostname in groups['vpn_primary'])

- include_tasks: ubuntu.yaml
  when: ansible_os_family|lower == 'debian'
